FROM node:18-alpine

WORKDIR /usr/workspace/test
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

ARG NEST_APP_MYSQL_HOST
ARG NEST_APP_MYSQL_PORT
ARG NEST_APP_MYSQL_USERNAME
ARG NEST_APP_MYSQL_PASSWORD

ENV NODE_ENV production
ENV NEST_APP_MYSQL_HOST ${NEST_APP_MYSQL_HOST}
ENV NEST_APP_MYSQL_PORT ${NEST_APP_MYSQL_PORT}
ENV NEST_APP_MYSQL_USERNAME ${NEST_APP_MYSQL_USERNAME}
ENV NEST_APP_MYSQL_PASSWORD ${NEST_APP_MYSQL_PASSWORD}
CMD ["node","dist/src/main.js"]
